export const DEFAULT_PET_BREED = "Doméstico (Mestizo/Quiltro)";

export const DOG_BREEDS = [
  "Doméstico (Mestizo/Quiltro)",
  "Affenpinscher",
  "Airedale Terrier",
  "Akita",
  "Akita americano",
  "American Bully",
  "American Staffordshire Terrier",
  "Antiguo perro pastor inglés",
  "Azawakh",
  "Basenji",
  "Basset artesiano normando",
  "Basset azul de Gascuña",
  "Basset hound",
  "Basset leonado de Bretaña",
  "Beagle",
  "Beagle Harrier",
  "Bearded Collie",
  "Bedlington Terrier",
  "Bichón frisé",
  "Bichón habanero",
  "Biewer Terrier",
  "Billy",
  "Boerboel",
  "Boloñés",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier de Flandes",
  "Bóxer",
  "Boyero australiano",
  "Boyero de Berna",
  "Boyero de Entlebuch",
  "Braco alemán de pelo corto",
  "Braco alemán de pelo duro",
  "Braco de Ariège",
  "Braco de Auvernia",
  "Braco de Borbón",
  "Braco húngaro",
  "Braco húngaro de pelo duro",
  "Braco italiano",
  "Bull Terrier",
  "Bull Terrier miniatura",
  "Bulldog americano",
  "Bulldog campeiro",
  "Bulldog francés",
  "Bulldog inglés",
  "Bulldog serrano",
  "Bullmastiff",
  "Cairn Terrier",
  "Calupoh",
  "Cane Corso",
  "Caniche",
  "Cavalier King Charles Spaniel",
  "Ceský Fousek",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chow Chow",
  "Chuandong Hound",
  "Cimarrón uruguayo",
  "Cirneco del Etna",
  "Clumber Spaniel",
  "Cocker Spaniel americano",
  "Cocker Spaniel inglés",
  "Collie de pelo corto",
  "Collie de pelo largo",
  "Coonhound negro y fuego",
  "Coton de Tuléar",
  "Crestado chino",
  "Dálmata",
  "Dandie Dinmont Terrier",
  "Deerhound",
  "Dóberman",
  "Dogo argentino",
  "Dogo de Burdeos",
  "Dogue Brasileiro",
  "Elkhound noruego gris",
  "Fila brasileño",
  "Fila de San Miguel",
  "Flat-Coated Retriever",
  "Fox Terrier de pelo duro",
  "Fox Terrier de pelo liso",
  "Foxhound americano",
  "Foxhound inglés",
  "Galgo español",
  "Gascón saintongeois",
  "Golden Retriever",
  "Gran azul de Gascuña",
  "Gran boyero suizo",
  "Gran danés",
  "Gran münsterländer",
  "Greyhound",
  "Grifón de Bruselas",
  "Grifón de muestra de pelo duro Korthals",
  "Grifón nivernais",
  "Hokkaido",
  "Husky siberiano",
  "Irish Soft Coated Wheaten Terrier",
  "Jack Russell Terrier",
  "Kelpie australiano",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Komondor",
  "Kromfohrländer",
  "Kuvasz",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Laizhou Hong",
  "Lakeland Terrier",
  "Landseer",
  "Lebrel afgano",
  "Leonberger",
  "Lhasa Apso",
  "Lobero irlandés",
  "Malamute de Alaska",
  "Maltés",
  "Manchester Terrier",
  "Mastiff",
  "Mastín del Pirineo",
  "Mastín español",
  "Mastín napolitano",
  "Mastín tibetano",
  "Monster Bull",
  "Mudi",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Ovejero gaúcho",
  "Ovejero magallánico",
  "Parson Russell Terrier",
  "Pastor alemán",
  "Pastor americano miniatura",
  "Pastor australiano",
  "Pastor belga",
  "Pastor blanco suizo",
  "Pastor de Asia Central",
  "Pastor de Beauce",
  "Pastor de Brie",
  "Pastor de Europa del Este",
  "Pastor de Kangal",
  "Pastor de la Mantiqueira",
  "Pastor de los Pirineos de cara rasa",
  "Pastor de los Pirineos de pelo largo",
  "Pastor de Shetland",
  "Pastor del Cáucaso",
  "Pastor finlandés de Laponia",
  "Pastor holandés",
  "Pastor maremmano-abruzzese",
  "Pastor polaco de las llanuras",
  "Pastor polaco de Tatra",
  "Pastor rumano de Bucovina",
  "Pekinés",
  "Pequeño azul de Gascuña",
  "Pequeño lebrel italiano",
  "Pequeño perro león",
  "Perdiguero portugués",
  "Perro de agua frisado",
  "Perro de agua portugués",
  "Perro de Canaán",
  "Perro de Castro Laboreiro",
  "Perro de Groenlandia",
  "Perro de la Sierra de la Estrella",
  "Perro de montaña de los Pirineos",
  "Perro de montaña del Atlas",
  "Perro de San Huberto",
  "Perro del faraón",
  "Perro lobo checoslovaco",
  "Perro sin pelo del Perú",
  "Petit Basset Griffon Vendéen",
  "Petit Brabançon",
  "Pinscher miniatura",
  "Pit Bull Terrier americano",
  "Podenco canario",
  "Podenco ibicenco",
  "Podengo andaluz",
  "Podengo portugués",
  "Pointer inglés",
  "Presa canario",
  "Pug",
  "Puli",
  "Pumi",
  "Rafeiro do Alentejo",
  "Rastreador brasileño",
  "Retriever de Nueva Escocia",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Sabueso fino colombiano",
  "Saluki",
  "Samoyedo",
  "San Bernardo",
  "Schipperke",
  "Schnauzer",
  "Schnauzer gigante",
  "Schnauzer miniatura",
  "Sealyham Terrier",
  "Setter Gordon",
  "Setter inglés",
  "Setter irlandés rojo",
  "Setter irlandés rojo y blanco",
  "Shar Pei",
  "Shiba",
  "Shih Tzu",
  "Shikoku",
  "Skye Terrier",
  "Smoushond holandés",
  "Spaniel bretón",
  "Spaniel continental enano (Papillon)",
  "Spaniel de agua americano",
  "Spaniel de agua irlandés",
  "Spaniel de Pont-Audemer",
  "Spaniel francés",
  "Spaniel japonés",
  "Spaniel picardo",
  "Spaniel tibetano",
  "Spinone italiano",
  "Spitz alemán",
  "Spitz finlandés",
  "Spitz japonés",
  "Springer Spaniel inglés",
  "Stabyhoun",
  "Staffordshire Bull Terrier",
  "Teckel estándar",
  "Teckel kaninchen",
  "Teckel miniatura",
  "Terranova",
  "Terrier alemán de caza",
  "Terrier americano sin pelo",
  "Terrier brasileño",
  "Terrier checo",
  "Terrier chileno",
  "Terrier escocés",
  "Terrier irlandés",
  "Terrier irlandés de Glen of Imaal",
  "Terrier negro ruso",
  "Terrier sedoso australiano",
  "Terrier tibetano",
  "Thai Ridgeback",
  "Tosa",
  "Toy Fox Terrier",
  "Treeing Walker Coonhound",
  "Veadeiro nacional",
  "Veadeiro pampeano",
  "Volpino italiano",
  "Weimaraner",
  "Welsh Corgi Cardigan",
  "Welsh Corgi Pembroke",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Xoloitzcuintle",
  "Yakutian Laika",
  "Yorkshire Terrier",
] as const;

export const CAT_BREEDS = [
  "Doméstico (Mestizo/Quiltro)",
  "Abisinio",
  "Azul ruso",
  "Bengal",
  "Bosque de Noruega",
  "Británico de pelo corto",
  "Cornish Rex",
  "Devon Rex",
  "Don Sphynx",
  "Exótico",
  "Lykoi",
  "Maine Coon",
  "Neva Masquerade",
  "Ocicat",
  "Oriental de pelo corto",
  "Persa",
  "Ragdoll",
  "Selkirk Rex",
  "Siamés",
  "Somalí",
  "Sphynx",
] as const;
